NumPy

# By Kishan0101

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_martix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_martix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_martix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Arange

Return evenly spaced values within a given interval

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10, 11, 2)

array([10])

In [12]:
np.arange(0, 2)

array([0, 1])

In [13]:
np.arange(0, 10, 15)

array([0])

In [14]:
np.arange(2, 4, 8)

array([2])

In [16]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [21]:
np.arange(2, 15, 3)
# Space b/w 2 and 15 of 3

array([ 2,  5,  8, 11, 14])

In [22]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

Zeros() and Ones()

Generate array of zero and one

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Linspace()

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number. 

In [30]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
np.linspace(0, 15, 3)

array([ 0. ,  7.5, 15. ])

In [32]:
np.linspace(0, 15, 10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [33]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye()

Create Identity Martix

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random()

Numpy also lots of ways to create random number arrays

Rand

To crate an array of th given shape and populate it with ramdom samples from a uniform distribution over[0, 1]

In [36]:
np.random.rand(2)

array([0.3522914 , 0.81720969])

In [38]:
np.random.rand(5, 5)

array([[0.24178968, 0.08709039, 0.24582571, 0.63930663, 0.70087139],
       [0.17771437, 0.76354298, 0.26305796, 0.57902236, 0.11396194],
       [0.03262051, 0.59873262, 0.88345835, 0.74672855, 0.31053392],
       [0.14371645, 0.42288135, 0.28394404, 0.70489453, 0.70283937],
       [0.79801469, 0.75537068, 0.01632417, 0.15203902, 0.23394805]])

Randn

Return a simple (or samples) from the "Standard normmal" distribution. unlike rand which is uniform:

In [39]:
np.random.randn(5)

array([-0.76642476,  0.23926946, -0.40201137, -0.39032477, -0.50965971])

In [40]:
np.random.randn(2)

array([ 1.0600721 , -2.09235735])

randint

Random number of intergers from low(inclusive) to high(exclusive).

In [41]:
np.random.randint(5)

4

In [42]:
np.random.randint(5)

2

In [43]:
np.random.randint(5)

1

In [44]:
np.random.randint(5)

4

In [45]:
np.random.randint(100)

21

In [46]:
np.random.randint(100)

47

Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [47]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
ranarr

array([27,  9, 33, 36, 41, 18, 49, 42, 24, 12])

 max,min,argmax,argmin


These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr

array([27,  9, 33, 36, 41, 18, 49, 42, 24, 12])

In [51]:
ranarr.max()

49

In [52]:
ranarr.min()

9

In [56]:
ranarr.argmin()

#argmin means indexing of min number of ranarr

1

In [55]:
ranarr.argmax()

#argmax means indexing of maximum number of rararr

6

 Shape

Shape is an attribute that arrays have (not a method):

In [58]:
# Vector
arr.shape

(25,)

In [60]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

 dtype
 
You can also grab the data type of the object in the array:

In [62]:
arr.dtype

dtype('int32')

In [ ]:
# Kishan0101