By Kishan0101

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[1:5]
#Start with 1 to 4

array([1, 2, 3, 4])

In [8]:
#set value in range 
arr[0:5]
#start with 1 and goes to 4

array([0, 1, 2, 3, 4])

 Broadcasting
 
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#setting a value with indexing range(Boardcasting)
arr[0:5] = 100
#indexing 0 to 4 equals 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [14]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# important notes on slice
slice_of_arr = arr[0:6]
#show
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
# Change of slice
slice_of_arr[:] = 100

In [22]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [23]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [24]:
#To get a copy, need to be expict
arr_copy = arr.copy

In [25]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

 Indexing a 2D array (matrices)
 
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [28]:
arr_2d = np.array(([10, 10, 10], [20, 20, 20], [30, 30, 30]))
arr_2d

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [30]:
arr_2d[1]

array([20, 20, 20])

In [31]:
arr_2d[1:2]

array([[20, 20, 20]])

In [33]:
arr_2d[1][0]
#1 row and 0 column values

20

In [34]:
arr_2d[1, 0]

20

In [35]:
# 2D array slicing
arr_2d[:2:1]

array([[10, 10, 10],
       [20, 20, 20]])

In [36]:
arr_2d[:2, 1:]

array([[10, 10],
       [20, 20]])

In [37]:
arr_2d[2]

array([30, 30, 30])

In [39]:
arr_2d[2:]

array([[30, 30, 30]])

In [40]:
arr_2d[:2]

array([[10, 10, 10],
       [20, 20, 20]])

In [41]:
arr_2d[:2, 2:]

array([[10],
       [20]])

In [42]:
arr_2d[0]

array([10, 10, 10])

In [44]:
arr_2d[2, 1]

30

In [45]:
arr_2d[2, 2]

30

In [46]:
arr_2d

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [48]:
arr_2d[2, 2]

30

In [49]:
arr_2d[0, 1]

10

 Fancy Indexing
 
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array

In [51]:
arr = np.zeros((10, 10))

In [52]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
arr_of_length = arr.shape[1]

In [55]:
arr_of_length

10

In [56]:
for i in range(arr_of_length):
    arr[i]*i

In [57]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
for i in range(arr_of_length):
    arr[i] = i
    arr

In [59]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [62]:
a = np.zeros((5, 5))

In [63]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
b = a.shape[0]

In [66]:
b

5

In [67]:
for i in range(b):
    a[i] = i

In [68]:
a

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [70]:
c  = np.zeros((6, 6))

In [71]:
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [75]:
for i in range(5):
    a[i] = i

In [76]:
a

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [77]:
d = np.ones((8, 8))

In [78]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [82]:
e = d.shape[0]

In [83]:
e

8

In [84]:
for i in range(e):
    d[i] = i


In [85]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7.]])

Fancy indexing allows the following

In [89]:
d[[1, 2, 3, 4]]

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.]])

In [90]:
d[[4, 5, 6]]

array([[4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.]])

In [91]:
d[[1, 2, 3]]

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.]])

In [92]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7.]])

In [93]:
d[[3, 2, 3, 6][1]]

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [94]:
d[[1]]

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [95]:
d[[2, 2, 2][2]]

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [98]:
d[[3, 2, 3, 7][1]]

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [99]:
d[[3, 2, 3, 7][::2]]

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3.]])

In [100]:
d[::2]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6.]])

In [101]:
d[[3, 2, 3, 2][::3]]

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2., 2., 2., 2.]])

In [104]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
bool_arr = a>4

In [108]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [110]:
a[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [111]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
a > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [113]:
x = 2
a[a>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])